player_name = input("What player would you like to calculate statistics for? ")
player_team = input("What team was the opponent in the game you would like to calculate statistics for? ")
attempt_3s = int(input("How many 3's did " + player_name + " attempt this game? "))
shot_3s = int(input("How many 3's did " + player_name + " make this game? "))
attempt_2s = int(input("How many 2's did " + player_name + " attempt this game? "))
shot_2s = int(input("How many 2's did " + player_name + " make this game? "))
attempt_free = int(input("How many free throws did " + player_name + " attempt this game? "))
shot_free = int(input("How many free throws did " + player_name + " make this game? "))
field_goal_percentage = str(((shot_3s + shot_2s)/(attempt_3s + attempt_2s))*100)
free_throw_percentage = str((shot_free/attempt_free)*100)
total_points = str((2*shot_2s) + (3*shot_3s) + shot_free)
print(player_name + " had a " + field_goal_percentage + "% field goal percentage and a " + free_throw_percentage + "% free throw percentage")
print(player_name + " scored " + total_points + " points against " + player_team + ". Wahoowa!")